### ISSUE TITLE
[Enhancement/Feature request] Add support for FF keyboard shortcut

### ISSUE THREAD

**Issue by fragande** [plneappl/streamlink-helper#10]
As topic states. Would it be possible to add support for Firefox's add-on shortcut feature? Using the context menu is cumbersome. As of today I use AHK to automatically navigate the menu, but it requires three different keybinds because the location of the "Open with Streamlink" entry changes depending on if you right click on the left pane/right pane on the Twitch page or playing stream. 

Having the context menu popping up isn't very elegant either. So having a simple global "Open with Streamlink" shortcut in FF would be awesome :)

**Comment by fragande** [comment]
After doing a bit of Googling it seems it should quite easy (from what I can tell) to add using [`commands`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands).

**Comment by plneappl** [comment]
Implemented via [4687029](https://github.com/plneappl/streamlink-helper/commit/468702930796c5adff6220145ed5ee03500abbd7), default is Ctrl+Alt+S. Should be live in the next 24h or so, feel free to close this if that works for you or tell me if anything is broken :)

**Comment by fragande** [comment]
> Implemented via [4687029](https://github.com/plneappl/streamlink-helper/commit/468702930796c5adff6220145ed5ee03500abbd7), default is Ctrl+Alt+S. Should be live in the next 24h or so, feel free to close this if that works for you or tell me if anything is broken :)

Amazing, thank you :) Works perfectly for opened streams, however the shortcut I was mainly craving was `Open with Streamlink` while hovering _links_ (if that's possible). Personally I very rarely open the stream in the browser, I just right-click on the link in followed list or live channels and `Open with Streamlink` that way (well, using AHK).

**Comment by plneappl** [comment]
Ah I see, let me check if I can find a way. I think I will need permission "modify all hosts" though...

**Comment by plneappl** [comment]
I think I got it, since I do need that "modify all pages" permission the review from Mozilla might take a while though ;)

**Comment by plneappl** [comment]
If you'd like you can try it out with debug install from the 1.3.0 release: https://github.com/plneappl/streamlink-helper/releases/tag/1.3.0

**Comment by plneappl** [comment]
Nope, review was fast, you'll get it with the next automatic update :)

**Comment by fragande** [comment]
> Nope, review was fast, you'll get it with the next automatic update :)

Incredible, works like a charm :) Thank you again.
