### ISSUE TITLE
Streamlink.exe

### ISSUE THREAD

**Issue by signalsout** [plneappl/streamlink-helper#8]
Hello, 
I have streamlink helper installed. When on Twitch and I right click play in streamlink the streamlink.exe command terminal opens and then closes. Like it's trying to load something. Then MPV for windows doesn't open. Do I specifically need to edit something to tell it to play in MPV? I have streamlink configured correctly. 

Thank you,
Nathan

**Comment by plneappl** [comment]
Have you followed the complete setup described here? https://github.com/plneappl/streamlink-helper
What happens when you try to launch any stream via console, for example `streamlink twitch.tv/<channel>`? Have you set `default-stream`?

**Comment by signalsout** [comment]
I works fine. I did the linking fine. A stream link.exe console panel loads and then closes without opening mpv like it normally does. 

—————
Nathan Koch

**Comment by plneappl** [comment]
Hm I'm not sure what the problem could be. You could try to look at the debug output of the python script, by commenting out line 23 in file `streamlink_helper.py` and adding a `pause` command at the end of `streamlink_helper.bat`.

**Comment by plneappl** [comment]
Just a reminder, if this is still an issue for you I'm happy to help, otherwise I'm gonna close this issue soon :)
