### ISSUE TITLE
Possible to hide Python console on Windows?

### ISSUE THREAD

**Issue by fragande** [plneappl/streamlink-helper#9]
As topic states, I'm wondering if it's possible to hide the Python console that opens on Windows and has to run while the stream is open. I would like it to run in the background to avoid clutter, for my other streamlink batch files I'm using SilentCMD to accomplish this.

Would it be possible to launch `pythonw.exe` instead of `python.exe` maybe?

**Comment by plneappl** [comment]
Sure, to run streamlink without a window (on windows), edit `streamlink_helper.py` and replace `subprocess.CREATE_NEW_CONSOLE` with `subprocess.CREATE_NO_WINDOW`. 
The problem is not actually the python process, but how you need to break away from the calling cmd, which is what this argument does.

**Comment by fragande** [comment]
> Sure, to run streamlink without a window (on windows), edit `streamlink_helper.py` and replace `subprocess.CREATE_NEW_CONSOLE` with `subprocess.CREATE_NO_WINDOW`. The problem is not actually the python process, but how you need to break away from the calling cmd, which is what this argument does.

Sorry, I have very little understanding of this stuff. I actually tried that already after some google-fu but I get the following .. error (?):

```
Response: Windows
	C:\*my_path*\streamlink_helper
	C:\WINDOWS\SYSTEM32\python27.zip
	C:\Python27\DLLs
	C:\Python27\lib
	C:\Python27\lib\plat-win
	C:\Python27\lib\lib-tk
	C:\Python27
	C:\Python27\lib\site-packages
	C:\Python27\lib\site-packages\win32
	C:\Python27\lib\site-packages\win32\lib
	C:\Python27\lib\site-packages\Pythonwin
```

Maybe it's Python3 dependent and Python 2.7 is my `PATH` version?

I also tried removing `subprocess.CREATE_NEW_CONSOLE` and adding `stdout = subprocess.PIPE` which "works" but I have no idea what this actually does ... heh.

**Comment by plneappl** [comment]
yeah I use python3
glad you found a solution!

**Comment by fragande** [comment]
Adding Python3 to `PATH` allowed me to use `CREATE_NO_WINDOW` instead of whatever I did. Thank you for the help :)
